stages:
  - generate-and-verify

variables:
  # Settings to fetch recursive repositories
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_DEPTH: 1

  # Global variables used across all included CI files
  TARGET_REPO_URL: "https://gitlab.cern.ch/joteig/madgraph5-gen-code-test.git"
  TARGET_REPO_NAME: "madgraph5-gen-code-test"

include:
  - local: '.gitlab/ci/codegen.gitlab-ci.yml'