name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  debug_builds:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: [ epochX/cudacpp/ee_mumu.sa/SubProcesses/P1_Sigma_sm_epem_mupmum , epochX/cudacpp/gg_tt.sa/SubProcesses/P1_Sigma_sm_gg_ttx , epochX/cudacpp/gg_ttg.sa/SubProcesses/P1_Sigma_sm_gg_ttxg , epochX/cudacpp/gg_ttgg.sa/SubProcesses/P1_Sigma_sm_gg_ttxgg , epochX/cudacpp/gg_ttggg.sa/SubProcesses/P1_Sigma_sm_gg_ttxggg ]
      fail-fast: false
    steps:

    - uses: actions/checkout@v2
    - name: make epochX
      run: make -C ${{ matrix.folder }} debug
  CPU:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: [ epochX/cudacpp/ee_mumu.sa/SubProcesses/P1_Sigma_sm_epem_mupmum , epochX/cudacpp/gg_tt.sa/SubProcesses/P1_Sigma_sm_gg_ttx , epochX/cudacpp/gg_ttg.sa/SubProcesses/P1_Sigma_sm_gg_ttxg , epochX/cudacpp/gg_ttgg.sa/SubProcesses/P1_Sigma_sm_gg_ttxgg , epochX/cudacpp/gg_ttggg.sa/SubProcesses/P1_Sigma_sm_gg_ttxggg ]
        precision: [ d , f , m ]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: make info
      run: make FPTYPE=${{ matrix.precision }} -C ${{ matrix.folder }} info
    - name: make
      run: make FPTYPE=${{ matrix.precision }} -C ${{ matrix.folder }}
    - name: make check
      run: make FPTYPE=${{ matrix.precision }} -C ${{ matrix.folder }} check
  CPU_MAC:
    runs-on: macos-latest
    env:
      FC: gfortran-11
    strategy:
      matrix:
        folder: [ epochX/cudacpp/ee_mumu.sa/SubProcesses/P1_Sigma_sm_epem_mupmum , epochX/cudacpp/gg_tt.sa/SubProcesses/P1_Sigma_sm_gg_ttx , epochX/cudacpp/gg_ttg.sa/SubProcesses/P1_Sigma_sm_gg_ttxg , epochX/cudacpp/gg_ttgg.sa/SubProcesses/P1_Sigma_sm_gg_ttxgg , epochX/cudacpp/gg_ttggg.sa/SubProcesses/P1_Sigma_sm_gg_ttxggg ]
        precision: [ d , f , m ]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: make info
      run: make AVX=none OMPFLAGS= FPTYPE=${{ matrix.precision }} -C ${{ matrix.folder }} info
    - name: make
      run: make AVX=none OMPFLAGS= FPTYPE=${{ matrix.precision }} -C ${{ matrix.folder }}
    - name: make check
      run: make AVX=none OMPFLAGS= FPTYPE=${{ matrix.precision }} -C ${{ matrix.folder }} check
  GPU:
    runs-on: [self-hosted, linux, v100s]
    env:
      CUDA_HOME: /usr/local/cuda/
      FC: gfortran
      REQUIRE_CUDA: 1
    strategy:
      matrix:
        folder: [ epochX/cudacpp/ee_mumu.sa/SubProcesses/P1_Sigma_sm_epem_mupmum , epochX/cudacpp/gg_tt.sa/SubProcesses/P1_Sigma_sm_gg_ttx , epochX/cudacpp/gg_ttg.sa/SubProcesses/P1_Sigma_sm_gg_ttxg , epochX/cudacpp/gg_ttgg.sa/SubProcesses/P1_Sigma_sm_gg_ttxgg , epochX/cudacpp/gg_ttggg.sa/SubProcesses/P1_Sigma_sm_gg_ttxggg ]
        precision: [ d , f , m ]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: path
      run: echo "PATH=$PATH"
    - name: make info
      run: source /cvmfs/sft.cern.ch/lcg/releases/gcc/11.3.0-ad0f5/x86_64-centos8/setup.sh; make FPTYPE=${{ matrix.precision }} -C ${{ matrix.folder }} info
    - name: make
      run: source /cvmfs/sft.cern.ch/lcg/releases/gcc/11.3.0-ad0f5/x86_64-centos8/setup.sh; make FPTYPE=${{ matrix.precision }} -C ${{ matrix.folder }}
    - name: make check
      run: source /cvmfs/sft.cern.ch/lcg/releases/gcc/11.3.0-ad0f5/x86_64-centos8/setup.sh; make FPTYPE=${{ matrix.precision }} -C ${{ matrix.folder }} check
