name: CUDA A100 Profiler

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cuda_a100_Profiling:
    name: CUDA A100 Profiling
    env:
      CUDA_NAME_PREFIX: cudacpp_AMD-Epyc-7313_a100_gcc-11.3_cuda-11.8
      ENABLE_CI_PROFILER: 1

      MADGRAPH4GPU_DB_SECRET: ${{ secrets.MADGRAPH4GPU_DB_SECRET }}
    runs-on: [self-hosted, linux, a100]
    steps:
    - uses: actions/checkout@v2
    - name: Runs CUDA performanceProfiler.py script
      run: cd tools/profiling/; source /cvmfs/sft.cern.ch/lcg/releases/gcc/11.3.0-ad0f5/x86_64-centos8/setup.sh; python3 performanceProfiler.py -l 'CUDA' -b 'master'
    - name: Uploads CUDA JSON files to DB
      run: cd tools/profiling/; python3 sendData.py --absLayer CUDA --profiler 1 --branch master