name: Profiler

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  NAME_PREFIX: sycl 

jobs:
  a100s_Profiling:
    name: A100S Profiling
    env:
      SYCL_NAME_PREFIX: sycl_Xeon-Silver-4216_a100s_gcc-11.3_cuda-11.6.2
      CUDA_NAME_PREFIX: cudacpp_Xeon-Silver-4216_a100s_gcc-11.3_cuda-11.6.2

      MADGRAPH4GPU_DB_SECRET: ${{ secrets.MADGRAPH4GPU_DB_SECRET }}
    runs-on: [self-hosted, linux, a100s]
    steps:
    - uses: actions/checkout@v2
    - name: Runs SYCL performanceProfiler.py script
      run: cd tools/profiling/; source /cvmfs/sft.cern.ch/lcg/contrib/gcc/11.3.0/x86_64-centos8/setup.sh; g++ --version; python3 performanceProfiler.py -l 'SYCL' -b 'master'
    - name: Uploads SYCL JSON files to DB
      run: ./tools/profiling/sendData.py --profiler --absLayer "SYCL"
    - name: Runs CUDA performanceProfiler.py script
      run: cd tools/profiling/; source /cvmfs/sft.cern.ch/lcg/contrib/gcc/11.3.0/x86_64-centos8/setup.sh; python3 performanceProfiler.py -l 'CUDA' -b 'master'
    - name: Uploads CUDA JSON files to DB
      run: ./tools/profiling/sendData.py --profiler --absLayer "CUDA"