name: SYCL A100 Profiler

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  sycl_A100_Profiling:
    name: SYCL A100 Profiling
    env:
      SYCL_NAME_PREFIX: sycl_AMD-Epyc-7313_a100_gcc-11.3_cuda-11.9
      ENABLE_CI_PROFILER: 1

      MADGRAPH4GPU_DB_SECRET: ${{ secrets.MADGRAPH4GPU_DB_SECRET }}
    runs-on: [self-hosted, linux, a100]
    steps:
    - uses: actions/checkout@v2
    - name: Runs SYCL performanceProfiler.py script
      run: cd tools/profiling/; source /cvmfs/sft.cern.ch/lcg/contrib/gcc/11.3.0/x86_64-centos8/setup.sh; python3 performanceProfiler.py -l 'SYCL' -b 'master'
    - name: Uploads SYCL JSON files to DB
      run: cd tools/profiling/; python3 sendData.py --absLayer SYCL --profiler --branch master