name: SYCL CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  GPU:
    runs-on: [self-hosted, linux, v100s]
    env:
      FC: gfortran
      REQUIRE_CUDA: 1
      SYCLFLAGS: -fsycl
      ENABLE_CI_PROFILER: 1
    strategy:
      matrix:
        folder: [ epochX/sycl/ee_mumu.sa/SubProcesses/P1_Sigma_sm_epem_mupmum , epochX/sycl/gg_tt.sa/SubProcesses/P1_Sigma_sm_gg_ttx , epochX/sycl/gg_ttg.sa/SubProcesses/P1_Sigma_sm_gg_ttxg , epochX/sycl/gg_ttgg.sa/SubProcesses/P1_Sigma_sm_gg_ttxgg , epochX/sycl/gg_ttggg.sa/SubProcesses/P1_Sigma_sm_gg_ttxggg ]
        precision: [ d , f ]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: make info
      run: source /cvmfs/sft.cern.ch/lcg/contrib/gcc/11.3.0/x86_64-centos8/setup.sh;
           CXX=/afs/cern.ch/work/j/jteig/sycl_workspace/llvm/build/bin/clang++;
           LD_LIBRARY_PATH=/afs/cern.ch/work/j/jteig/sycl_workspace/llvm/build/lib:$LD_LIBRARY_PATH
           export CUDA_HOME=/usr/local/cuda-11.6/;
           make FPTYPE=${{ matrix.precision }} -C ${{ matrix.folder }} info
    - name: make
      run: source /cvmfs/sft.cern.ch/lcg/contrib/gcc/11.3.0/x86_64-centos8/setup.sh;
           CXX=/afs/cern.ch/work/j/jteig/sycl_workspace/llvm/build/bin/clang++;
           LD_LIBRARY_PATH=/afs/cern.ch/work/j/jteig/sycl_workspace/llvm/build/lib:$LD_LIBRARY_PATH
           export CUDA_HOME=/usr/local/cuda-11.6/;
           make FPTYPE=${{ matrix.precision }} -C ${{ matrix.folder }}
    - name: make check
      run: source /cvmfs/sft.cern.ch/lcg/contrib/gcc/11.3.0/x86_64-centos8/setup.sh; 
           CXX=/afs/cern.ch/work/j/jteig/sycl_workspace/llvm/build/bin/clang++;
           LD_LIBRARY_PATH=/afs/cern.ch/work/j/jteig/sycl_workspace/llvm/build/lib:$LD_LIBRARY_PATH
           export CUDA_HOME=/usr/local/cuda-11.6/;
           make FPTYPE=${{ matrix.precision }} -C ${{ matrix.folder }} check